### ISSUE TITLE
[PE-D][Tester E] addPerson should not default to the first company if no company index provided

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T15-4/tp#157]
This default behavior can be unintuitive for users and cause the users to accidentally add the wrong people to the first company if they missed the `c/` parameter. 

Additionally, the documentation states that if any of the details are invalid or wrong, then the following error: "Please provide valid contact details including name, phone, email, address, and a valid company index." will be displayed but the part about "a valid company index" goes against this default behavior, thus potentially causing confusion

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: woojiahao/ped#8

**Comment by geraldngjx** [comment]
We intended to automatically assign the user to the first company index instead of flagging up that the command format is invalid as users might want to automatically add contacts to the most recent company that they have added, thus it is a feature that we wished to include to increase the efficiency of adding connections.
